#!/usr/bin/env bash
# =============================================================================
# APIx VM Setup Script — runs on a fresh Ubuntu 22.04 / 24.04 server
# Compatible with Oracle Cloud Free Tier (ARM A1.Flex, always free)
#              and DigitalOcean / Hetzner / any VPS (~$6/month)
#
# WHAT THIS DOES
# --------------
# 1. Installs Python 3.12, Docker, Playwright Chromium
# 2. Clones this repo (or uses existing checkout)
# 3. Creates a systemd service + cron to run `make scrape` daily at 02:00 IST
# 4. Sets up `make index` + `make export` at 04:30 IST
#
# USAGE
# -----
#   git clone https://github.com/TushKum/apix-airfare-index.git /srv/apix
#   cd /srv/apix
#   cp .env.example .env
#   # Edit .env: set DATABASE_URL, set APIX_USE_SEED_DATA=false for live data
#   sudo bash scripts/setup_vm.sh
#
# ENVIRONMENT VARIABLES (set in .env before running this script)
# ---------------------------------------------------------------
#   DATABASE_URL          postgresql://apix:apix@localhost:5433/apix
#   APIX_USE_SEED_DATA    false   ← must be false for real fare collection
#   APIX_IDENTITY_MODE    identified
#   APIX_MIN_DELAY_SECONDS 8.0
# =============================================================================
set -euo pipefail

REPO_DIR="${REPO_DIR:-/srv/apix}"
APIX_USER="${APIX_USER:-apix}"
LOG_DIR="/var/log/apix"
CRON_FILE="/etc/cron.d/apix"

echo "=== APIx VM Setup ==="
echo "Repo: $REPO_DIR"
echo "User: $APIX_USER"
echo ""

# ── 0. Must run as root ──────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run this as root: sudo bash scripts/setup_vm.sh" >&2
  exit 1
fi

# ── 1. System packages ───────────────────────────────────────────────────────
echo "[1/7] Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
  python3.12 python3.12-venv python3-pip \
  docker.io docker-compose \
  postgresql-client \
  curl git cron

# ── 2. Create apix user ──────────────────────────────────────────────────────
echo "[2/7] Creating system user '$APIX_USER'..."
id "$APIX_USER" &>/dev/null || useradd -r -m -d "$REPO_DIR" -s /bin/bash "$APIX_USER"
usermod -aG docker "$APIX_USER"

# ── 3. Clone repo (if not already there) ─────────────────────────────────────
echo "[3/7] Setting up repo at $REPO_DIR..."
if [[ ! -d "$REPO_DIR/.git" ]]; then
  git clone https://github.com/TushKum/apix-airfare-index.git "$REPO_DIR"
fi
chown -R "$APIX_USER:$APIX_USER" "$REPO_DIR"

# ── 4. Python venv + deps + Playwright ───────────────────────────────────────
echo "[4/7] Installing Python dependencies..."
sudo -u "$APIX_USER" bash -c "
  cd $REPO_DIR
  python3.12 -m venv .venv
  .venv/bin/pip install --quiet --upgrade pip
  .venv/bin/pip install --quiet -r requirements.txt
  .venv/bin/playwright install chromium
  .venv/bin/playwright install-deps chromium
"

# ── 5. Start Postgres with Docker ────────────────────────────────────────────
echo "[5/7] Starting PostgreSQL..."
systemctl enable docker --now
sudo -u "$APIX_USER" bash -c "
  cd $REPO_DIR
  docker-compose up -d db
"
# Wait for Postgres to be ready
for i in {1..20}; do
  sudo -u "$APIX_USER" bash -c "
    cd $REPO_DIR && source .env 2>/dev/null || true
    .venv/bin/python -c \"
import psycopg2, os
psycopg2.connect(os.getenv('DATABASE_URL','postgresql://apix:apix@localhost:5433/apix'))
\"" 2>/dev/null && break
  echo "  waiting for Postgres ($i/20)..."
  sleep 3
done

# Apply schema
sudo -u "$APIX_USER" bash -c "
  cd $REPO_DIR
  source .env 2>/dev/null || true
  psql \"\${DATABASE_URL:-postgresql://apix:apix@localhost:5433/apix}\" -f db/schema.sql
"

# ── 6. Load reference data + seed demo (once) ────────────────────────────────
echo "[6/7] Loading reference data and running initial demo seed..."
sudo -u "$APIX_USER" bash -c "
  cd $REPO_DIR
  source .venv/bin/activate
  source .env 2>/dev/null || true
  python scripts/load_reference.py || echo '  reference data not loaded (add CSV first)'
  make demo || echo '  demo seed completed (or already seeded)'
"

# ── 7. Install cron ──────────────────────────────────────────────────────────
echo "[7/7] Installing cron schedule..."
mkdir -p "$LOG_DIR"
chown "$APIX_USER:$APIX_USER" "$LOG_DIR"

cat > "$CRON_FILE" << CRON
# APIx daily collection pipeline
# Generated by scripts/setup_vm.sh — edit here, not in crontab -e
CRON_TZ=Asia/Kolkata
SHELL=/bin/bash

# 02:00 IST — collect airfares for today's date across the route x window matrix
0 2 * * *  $APIX_USER  cd $REPO_DIR && source .venv/bin/activate && make scrape  >> $LOG_DIR/scrape.log 2>&1

# 04:30 IST — build the index from whatever was collected (or seeded)
30 4 * * *  $APIX_USER  cd $REPO_DIR && source .venv/bin/activate && make index   >> $LOG_DIR/index.log  2>&1

# 05:00 IST — record any cells that yesterday's cycle missed; never invents data
0 5 * * *   $APIX_USER  cd $REPO_DIR && source .venv/bin/activate && python -m apix.cli backfill --date yesterday >> $LOG_DIR/backfill.log 2>&1

# 05:10 IST — export the updated dashboard JSON (Vercel picks it up on next deploy)
10 5 * * *  $APIX_USER  cd $REPO_DIR && source .venv/bin/activate && python scripts/export_dashboard.py >> $LOG_DIR/export.log 2>&1
CRON
chmod 644 "$CRON_FILE"

# Reload cron
service cron reload || systemctl reload cron || true

echo ""
echo "========================================================"
echo " Setup complete!"
echo "========================================================"
echo ""
echo " NEXT STEPS:"
echo "   1. Edit $REPO_DIR/.env"
echo "      — Set APIX_USE_SEED_DATA=false  (to collect real fares)"
echo "      — Verify DATABASE_URL is correct"
echo ""
echo "   2. Test the scraper manually:"
echo "      sudo -u $APIX_USER bash -c 'cd $REPO_DIR && source .venv/bin/activate && make scrape-plan'"
echo "      sudo -u $APIX_USER bash -c 'cd $REPO_DIR && source .venv/bin/activate && make scrape'"
echo ""
echo "   3. Check logs daily at:"
echo "      tail -f $LOG_DIR/scrape.log"
echo "      tail -f $LOG_DIR/index.log"
echo ""
echo "   4. Verify the data is real (not synthetic) via the API:"
echo "      curl https://apix-india.vercel.app/health/scrape | python3 -m json.tool"
echo "      Look for: \"status\": \"live\" and \"days_of_real_data\" > 0"
echo ""
echo "   5. After 30 days of real data, notify MoSPI via the problem statement portal."
echo ""
echo " Cron schedule installed at: $CRON_FILE"
echo " Logs at: $LOG_DIR/"
